/* Auto-generated by genmsg_cpp for file /home/pauline/Desktop/se306p1/ros/stacks/Project2Sample/srv/returnPosition.srv */
#ifndef PROJECT2SAMPLE_SERVICE_RETURNPOSITION_H
#define PROJECT2SAMPLE_SERVICE_RETURNPOSITION_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"

#include "ros/service_traits.h"




namespace Project2Sample
{
template <class ContainerAllocator>
struct returnPositionRequest_ {
  typedef returnPositionRequest_<ContainerAllocator> Type;

  returnPositionRequest_()
  {
  }

  returnPositionRequest_(const ContainerAllocator& _alloc)
  {
  }


private:
  static const char* __s_getDataType_() { return "Project2Sample/returnPositionRequest"; }
public:
  ROS_DEPRECATED static const std::string __s_getDataType() { return __s_getDataType_(); }

  ROS_DEPRECATED const std::string __getDataType() const { return __s_getDataType_(); }

private:
  static const char* __s_getMD5Sum_() { return "d41d8cd98f00b204e9800998ecf8427e"; }
public:
  ROS_DEPRECATED static const std::string __s_getMD5Sum() { return __s_getMD5Sum_(); }

  ROS_DEPRECATED const std::string __getMD5Sum() const { return __s_getMD5Sum_(); }

private:
  static const char* __s_getServerMD5Sum_() { return "938fa65709584ad8e77d238529be13b8"; }
public:
  ROS_DEPRECATED static const std::string __s_getServerMD5Sum() { return __s_getServerMD5Sum_(); }

  ROS_DEPRECATED const std::string __getServerMD5Sum() const { return __s_getServerMD5Sum_(); }

private:
  static const char* __s_getMessageDefinition_() { return "\n\
"; }
public:
  ROS_DEPRECATED static const std::string __s_getMessageDefinition() { return __s_getMessageDefinition_(); }

  ROS_DEPRECATED const std::string __getMessageDefinition() const { return __s_getMessageDefinition_(); }

  ROS_DEPRECATED virtual uint8_t *serialize(uint8_t *write_ptr, uint32_t seq) const
  {
    ros::serialization::OStream stream(write_ptr, 1000000000);
    return stream.getData();
  }

  ROS_DEPRECATED virtual uint8_t *deserialize(uint8_t *read_ptr)
  {
    ros::serialization::IStream stream(read_ptr, 1000000000);
    return stream.getData();
  }

  ROS_DEPRECATED virtual uint32_t serializationLength() const
  {
    uint32_t size = 0;
    return size;
  }

  typedef boost::shared_ptr< ::Project2Sample::returnPositionRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::Project2Sample::returnPositionRequest_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct returnPositionRequest
typedef  ::Project2Sample::returnPositionRequest_<std::allocator<void> > returnPositionRequest;

typedef boost::shared_ptr< ::Project2Sample::returnPositionRequest> returnPositionRequestPtr;
typedef boost::shared_ptr< ::Project2Sample::returnPositionRequest const> returnPositionRequestConstPtr;


template <class ContainerAllocator>
struct returnPositionResponse_ {
  typedef returnPositionResponse_<ContainerAllocator> Type;

  returnPositionResponse_()
  : x(0.0)
  , y(0.0)
  , theta(0.0)
  {
  }

  returnPositionResponse_(const ContainerAllocator& _alloc)
  : x(0.0)
  , y(0.0)
  , theta(0.0)
  {
  }

  typedef double _x_type;
  double x;

  typedef double _y_type;
  double y;

  typedef double _theta_type;
  double theta;


private:
  static const char* __s_getDataType_() { return "Project2Sample/returnPositionResponse"; }
public:
  ROS_DEPRECATED static const std::string __s_getDataType() { return __s_getDataType_(); }

  ROS_DEPRECATED const std::string __getDataType() const { return __s_getDataType_(); }

private:
  static const char* __s_getMD5Sum_() { return "938fa65709584ad8e77d238529be13b8"; }
public:
  ROS_DEPRECATED static const std::string __s_getMD5Sum() { return __s_getMD5Sum_(); }

  ROS_DEPRECATED const std::string __getMD5Sum() const { return __s_getMD5Sum_(); }

private:
  static const char* __s_getServerMD5Sum_() { return "938fa65709584ad8e77d238529be13b8"; }
public:
  ROS_DEPRECATED static const std::string __s_getServerMD5Sum() { return __s_getServerMD5Sum_(); }

  ROS_DEPRECATED const std::string __getServerMD5Sum() const { return __s_getServerMD5Sum_(); }

private:
  static const char* __s_getMessageDefinition_() { return "float64 x\n\
float64 y\n\
float64 theta\n\
\n\
\n\
"; }
public:
  ROS_DEPRECATED static const std::string __s_getMessageDefinition() { return __s_getMessageDefinition_(); }

  ROS_DEPRECATED const std::string __getMessageDefinition() const { return __s_getMessageDefinition_(); }

  ROS_DEPRECATED virtual uint8_t *serialize(uint8_t *write_ptr, uint32_t seq) const
  {
    ros::serialization::OStream stream(write_ptr, 1000000000);
    ros::serialization::serialize(stream, x);
    ros::serialization::serialize(stream, y);
    ros::serialization::serialize(stream, theta);
    return stream.getData();
  }

  ROS_DEPRECATED virtual uint8_t *deserialize(uint8_t *read_ptr)
  {
    ros::serialization::IStream stream(read_ptr, 1000000000);
    ros::serialization::deserialize(stream, x);
    ros::serialization::deserialize(stream, y);
    ros::serialization::deserialize(stream, theta);
    return stream.getData();
  }

  ROS_DEPRECATED virtual uint32_t serializationLength() const
  {
    uint32_t size = 0;
    size += ros::serialization::serializationLength(x);
    size += ros::serialization::serializationLength(y);
    size += ros::serialization::serializationLength(theta);
    return size;
  }

  typedef boost::shared_ptr< ::Project2Sample::returnPositionResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::Project2Sample::returnPositionResponse_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct returnPositionResponse
typedef  ::Project2Sample::returnPositionResponse_<std::allocator<void> > returnPositionResponse;

typedef boost::shared_ptr< ::Project2Sample::returnPositionResponse> returnPositionResponsePtr;
typedef boost::shared_ptr< ::Project2Sample::returnPositionResponse const> returnPositionResponseConstPtr;

struct returnPosition
{

typedef returnPositionRequest Request;
typedef returnPositionResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;
}; // struct returnPosition
} // namespace Project2Sample

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::Project2Sample::returnPositionRequest_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::Project2Sample::returnPositionRequest_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::Project2Sample::returnPositionRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "d41d8cd98f00b204e9800998ecf8427e";
  }

  static const char* value(const  ::Project2Sample::returnPositionRequest_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0xd41d8cd98f00b204ULL;
  static const uint64_t static_value2 = 0xe9800998ecf8427eULL;
};

template<class ContainerAllocator>
struct DataType< ::Project2Sample::returnPositionRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "Project2Sample/returnPositionRequest";
  }

  static const char* value(const  ::Project2Sample::returnPositionRequest_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::Project2Sample::returnPositionRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "\n\
";
  }

  static const char* value(const  ::Project2Sample::returnPositionRequest_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct IsFixedSize< ::Project2Sample::returnPositionRequest_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros


namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::Project2Sample::returnPositionResponse_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::Project2Sample::returnPositionResponse_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::Project2Sample::returnPositionResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "938fa65709584ad8e77d238529be13b8";
  }

  static const char* value(const  ::Project2Sample::returnPositionResponse_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0x938fa65709584ad8ULL;
  static const uint64_t static_value2 = 0xe77d238529be13b8ULL;
};

template<class ContainerAllocator>
struct DataType< ::Project2Sample::returnPositionResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "Project2Sample/returnPositionResponse";
  }

  static const char* value(const  ::Project2Sample::returnPositionResponse_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::Project2Sample::returnPositionResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "float64 x\n\
float64 y\n\
float64 theta\n\
\n\
\n\
";
  }

  static const char* value(const  ::Project2Sample::returnPositionResponse_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct IsFixedSize< ::Project2Sample::returnPositionResponse_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::Project2Sample::returnPositionRequest_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct returnPositionRequest_
} // namespace serialization
} // namespace ros


namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::Project2Sample::returnPositionResponse_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.x);
    stream.next(m.y);
    stream.next(m.theta);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct returnPositionResponse_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace service_traits
{
template<>
struct MD5Sum<Project2Sample::returnPosition> {
  static const char* value() 
  {
    return "938fa65709584ad8e77d238529be13b8";
  }

  static const char* value(const Project2Sample::returnPosition&) { return value(); } 
};

template<>
struct DataType<Project2Sample::returnPosition> {
  static const char* value() 
  {
    return "Project2Sample/returnPosition";
  }

  static const char* value(const Project2Sample::returnPosition&) { return value(); } 
};

template<class ContainerAllocator>
struct MD5Sum<Project2Sample::returnPositionRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "938fa65709584ad8e77d238529be13b8";
  }

  static const char* value(const Project2Sample::returnPositionRequest_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct DataType<Project2Sample::returnPositionRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "Project2Sample/returnPosition";
  }

  static const char* value(const Project2Sample::returnPositionRequest_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct MD5Sum<Project2Sample::returnPositionResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "938fa65709584ad8e77d238529be13b8";
  }

  static const char* value(const Project2Sample::returnPositionResponse_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct DataType<Project2Sample::returnPositionResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "Project2Sample/returnPosition";
  }

  static const char* value(const Project2Sample::returnPositionResponse_<ContainerAllocator> &) { return value(); } 
};

} // namespace service_traits
} // namespace ros

#endif // PROJECT2SAMPLE_SERVICE_RETURNPOSITION_H

