/* Auto-generated by genmsg_cpp for file /home/veniora/repos/se306p1/ros/stacks/Project2Sample/msg/State.msg */
#ifndef PROJECT2SAMPLE_MESSAGE_STATE_H
#define PROJECT2SAMPLE_MESSAGE_STATE_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"


namespace Project2Sample
{
template <class ContainerAllocator>
struct State_ {
  typedef State_<ContainerAllocator> Type;

  State_()
  : state(0)
  {
  }

  State_(const ContainerAllocator& _alloc)
  : state(0)
  {
  }

  typedef int64_t _state_type;
  int64_t state;


private:
  static const char* __s_getDataType_() { return "Project2Sample/State"; }
public:
  ROS_DEPRECATED static const std::string __s_getDataType() { return __s_getDataType_(); }

  ROS_DEPRECATED const std::string __getDataType() const { return __s_getDataType_(); }

private:
  static const char* __s_getMD5Sum_() { return "979940cbf4c11dcaa39d4ce8683ecc86"; }
public:
  ROS_DEPRECATED static const std::string __s_getMD5Sum() { return __s_getMD5Sum_(); }

  ROS_DEPRECATED const std::string __getMD5Sum() const { return __s_getMD5Sum_(); }

private:
  static const char* __s_getMessageDefinition_() { return "int64 state\n\
"; }
public:
  ROS_DEPRECATED static const std::string __s_getMessageDefinition() { return __s_getMessageDefinition_(); }

  ROS_DEPRECATED const std::string __getMessageDefinition() const { return __s_getMessageDefinition_(); }

  ROS_DEPRECATED virtual uint8_t *serialize(uint8_t *write_ptr, uint32_t seq) const
  {
    ros::serialization::OStream stream(write_ptr, 1000000000);
    ros::serialization::serialize(stream, state);
    return stream.getData();
  }

  ROS_DEPRECATED virtual uint8_t *deserialize(uint8_t *read_ptr)
  {
    ros::serialization::IStream stream(read_ptr, 1000000000);
    ros::serialization::deserialize(stream, state);
    return stream.getData();
  }

  ROS_DEPRECATED virtual uint32_t serializationLength() const
  {
    uint32_t size = 0;
    size += ros::serialization::serializationLength(state);
    return size;
  }

  typedef boost::shared_ptr< ::Project2Sample::State_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::Project2Sample::State_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct State
typedef  ::Project2Sample::State_<std::allocator<void> > State;

typedef boost::shared_ptr< ::Project2Sample::State> StatePtr;
typedef boost::shared_ptr< ::Project2Sample::State const> StateConstPtr;


template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const  ::Project2Sample::State_<ContainerAllocator> & v)
{
  ros::message_operations::Printer< ::Project2Sample::State_<ContainerAllocator> >::stream(s, "", v);
  return s;}

} // namespace Project2Sample

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::Project2Sample::State_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::Project2Sample::State_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::Project2Sample::State_<ContainerAllocator> > {
  static const char* value() 
  {
    return "979940cbf4c11dcaa39d4ce8683ecc86";
  }

  static const char* value(const  ::Project2Sample::State_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0x979940cbf4c11dcaULL;
  static const uint64_t static_value2 = 0xa39d4ce8683ecc86ULL;
};

template<class ContainerAllocator>
struct DataType< ::Project2Sample::State_<ContainerAllocator> > {
  static const char* value() 
  {
    return "Project2Sample/State";
  }

  static const char* value(const  ::Project2Sample::State_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::Project2Sample::State_<ContainerAllocator> > {
  static const char* value() 
  {
    return "int64 state\n\
";
  }

  static const char* value(const  ::Project2Sample::State_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct IsFixedSize< ::Project2Sample::State_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::Project2Sample::State_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.state);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct State_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::Project2Sample::State_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const  ::Project2Sample::State_<ContainerAllocator> & v) 
  {
    s << indent << "state: ";
    Printer<int64_t>::stream(s, indent + "  ", v.state);
  }
};


} // namespace message_operations
} // namespace ros

#endif // PROJECT2SAMPLE_MESSAGE_STATE_H

