/* Auto-generated by genmsg_cpp for file /home/ubuntu-11-10/se306p1/ros/stacks/Project2Sample/msg/VelocityInstructions.msg */
#ifndef PROJECT2SAMPLE_MESSAGE_VELOCITYINSTRUCTIONS_H
#define PROJECT2SAMPLE_MESSAGE_VELOCITYINSTRUCTIONS_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"


namespace Project2Sample
{
template <class ContainerAllocator>
struct VelocityInstructions_ {
  typedef VelocityInstructions_<ContainerAllocator> Type;

  VelocityInstructions_()
  : linearV(0.0)
  , angularV(0.0)
  {
  }

  VelocityInstructions_(const ContainerAllocator& _alloc)
  : linearV(0.0)
  , angularV(0.0)
  {
  }

  typedef double _linearV_type;
  double linearV;

  typedef double _angularV_type;
  double angularV;


private:
  static const char* __s_getDataType_() { return "Project2Sample/VelocityInstructions"; }
public:
  ROS_DEPRECATED static const std::string __s_getDataType() { return __s_getDataType_(); }

  ROS_DEPRECATED const std::string __getDataType() const { return __s_getDataType_(); }

private:
  static const char* __s_getMD5Sum_() { return "375c38002a3bdf6dbd092670630f2c8d"; }
public:
  ROS_DEPRECATED static const std::string __s_getMD5Sum() { return __s_getMD5Sum_(); }

  ROS_DEPRECATED const std::string __getMD5Sum() const { return __s_getMD5Sum_(); }

private:
  static const char* __s_getMessageDefinition_() { return "float64 linearV\n\
float64 angularV\n\
\n\
"; }
public:
  ROS_DEPRECATED static const std::string __s_getMessageDefinition() { return __s_getMessageDefinition_(); }

  ROS_DEPRECATED const std::string __getMessageDefinition() const { return __s_getMessageDefinition_(); }

  ROS_DEPRECATED virtual uint8_t *serialize(uint8_t *write_ptr, uint32_t seq) const
  {
    ros::serialization::OStream stream(write_ptr, 1000000000);
    ros::serialization::serialize(stream, linearV);
    ros::serialization::serialize(stream, angularV);
    return stream.getData();
  }

  ROS_DEPRECATED virtual uint8_t *deserialize(uint8_t *read_ptr)
  {
    ros::serialization::IStream stream(read_ptr, 1000000000);
    ros::serialization::deserialize(stream, linearV);
    ros::serialization::deserialize(stream, angularV);
    return stream.getData();
  }

  ROS_DEPRECATED virtual uint32_t serializationLength() const
  {
    uint32_t size = 0;
    size += ros::serialization::serializationLength(linearV);
    size += ros::serialization::serializationLength(angularV);
    return size;
  }

  typedef boost::shared_ptr< ::Project2Sample::VelocityInstructions_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::Project2Sample::VelocityInstructions_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct VelocityInstructions
typedef  ::Project2Sample::VelocityInstructions_<std::allocator<void> > VelocityInstructions;

typedef boost::shared_ptr< ::Project2Sample::VelocityInstructions> VelocityInstructionsPtr;
typedef boost::shared_ptr< ::Project2Sample::VelocityInstructions const> VelocityInstructionsConstPtr;


template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const  ::Project2Sample::VelocityInstructions_<ContainerAllocator> & v)
{
  ros::message_operations::Printer< ::Project2Sample::VelocityInstructions_<ContainerAllocator> >::stream(s, "", v);
  return s;}

} // namespace Project2Sample

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::Project2Sample::VelocityInstructions_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::Project2Sample::VelocityInstructions_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::Project2Sample::VelocityInstructions_<ContainerAllocator> > {
  static const char* value() 
  {
    return "375c38002a3bdf6dbd092670630f2c8d";
  }

  static const char* value(const  ::Project2Sample::VelocityInstructions_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0x375c38002a3bdf6dULL;
  static const uint64_t static_value2 = 0xbd092670630f2c8dULL;
};

template<class ContainerAllocator>
struct DataType< ::Project2Sample::VelocityInstructions_<ContainerAllocator> > {
  static const char* value() 
  {
    return "Project2Sample/VelocityInstructions";
  }

  static const char* value(const  ::Project2Sample::VelocityInstructions_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::Project2Sample::VelocityInstructions_<ContainerAllocator> > {
  static const char* value() 
  {
    return "float64 linearV\n\
float64 angularV\n\
\n\
";
  }

  static const char* value(const  ::Project2Sample::VelocityInstructions_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct IsFixedSize< ::Project2Sample::VelocityInstructions_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::Project2Sample::VelocityInstructions_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.linearV);
    stream.next(m.angularV);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct VelocityInstructions_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::Project2Sample::VelocityInstructions_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const  ::Project2Sample::VelocityInstructions_<ContainerAllocator> & v) 
  {
    s << indent << "linearV: ";
    Printer<double>::stream(s, indent + "  ", v.linearV);
    s << indent << "angularV: ";
    Printer<double>::stream(s, indent + "  ", v.angularV);
  }
};


} // namespace message_operations
} // namespace ros

#endif // PROJECT2SAMPLE_MESSAGE_VELOCITYINSTRUCTIONS_H

